### PR TITLE
project details added

### PR DESCRIPTION
**Pull request by divyaprakash-Rx**
details of all the projects added

### CODE REVIEW

**Comment by divyaprakash-Rx** [comment]
@TeAmP0is0N I have added the same details. please review and merge my pull request.

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx Please add the ss.

**Comment by divyaprakash-Rx** [comment]
Screenshot (92)
@TeAmP0is0N please check.

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx These all description should be column wise.

**Comment by divyaprakash-Rx** [comment]
Means all 4 in a column

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx No, there should be 4 columns for all 4 products.

**Comment by divyaprakash-Rx** [comment]
Yes, I understood.

**Comment by divyaprakash-Rx** [comment]
Screenshot (93)
@TeAmP0is0N I have updated.
Please review and merge my pull request.

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx Can you remove numbers and make it more interactive to use design patterns like colors and fonts and you can also add a background.

**Comment by divyaprakash-Rx** [comment]
Ok

**Comment by divyaprakash-Rx** [comment]
@TeAmP0is0N I have added cards design with background and shadow. Please review.
Screenshot (95)

**Comment by swapagarwal** [comment]
Thanks @divyaprakash-Rx! 👍

**Pull request merged**
