### PR TITLE
Add ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by Aman-Codes**
@TeAmP0is0N Added a pull request template and an issue template folder with bug_report_template.md and feature_request_template.md.
Closes: #20

### CODE REVIEW

**Comment by abhu-A-J** [comment]
@TeAmP0is0N Sir, I think the PR template can be changed to make a little less intensive. Section like Checklist is not required because no code guidelines is given on the README to follow (specs like indent spacing, adding comments etc.) 
Also pull request can have section where we can add labels so mentors can easily know about it)

**Comment by Aman-Codes** [comment]
@abhu-A-J Thanks for the valuable feedback.
I added the the label field so that participant can add labels like bug, enhancement etc. It was definitely not meant for adding difficulty level labels.
The check list was added because it is a common issue faced by the mentors in general that participants do not follow the proper coding guidelines and conventions. It was added just to ensure that the participants review their changes properly before submitting a pull request.

Still if the mentors want the above mentioned changes to be done. I would definitely do them.

**Comment by TeAmP0is0N** [comment]
@abhu-A-J You can remove the label field because we have to decide the label of issues.

**Comment by Aman-Codes** [comment]
@TeAmP0is0N Ok sir I will remove the label field from all my pull request.

**Comment by Aman-Codes** [comment]
@TeAmP0is0N Sir did the asked changes. Please review it and do let me know if any changes are required.

**Comment by swapagarwal** [comment]
Thanks @Aman-Codes! 👍

**Pull request merged**
