### PR TITLE
Template for chat section Jarvis UI

### PR DESCRIPTION
**Pull request by divyaprakash-Rx**
4 templates corresponding to color and mode are created.

### CODE REVIEW

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx  Add your screenshot.

**Comment by TeAmP0is0N** [comment]
@divyaprakash-Rx  Whatever changes you have made. Add ss.

**Comment by divyaprakash-Rx** [comment]
Full chat UI Light
1 on 1 chat UI dark
1 on 1 chat UI light
Full Chat UI dark

**Comment by divyaprakash-Rx** [comment]
@TeAmP0is0N  please check if design is fine or not. After that, please assign me to code.

**Comment by tanisha03** [comment]
@divyaprakash-Rx consider the current template in mind while designing. I have assigned it to you, you can keep working

**Comment by divyaprakash-Rx** [comment]
OK, I am using this design.

**Comment by divyaprakash-Rx** [comment]
@tanisha03 @TeAmP0is0N I have completed the ui page.
Please merge my pull request.
These are screenshots.
Screenshot (84)
Screenshot (83)


Screenshot (85)

**Comment by swapagarwal** [comment]
@divyaprakash-Rx Please rebase on top of current master and remove non-essential files like `.vs/*`

**Comment by divyaprakash-Rx** [comment]
@swapagarwal Ok, I am adding files according to new master base.

**Comment by divyaprakash-Rx** [comment]
@swapagarwal I have rebased on top of current master.
Please merge my pull request.

**Comment by swapagarwal** [comment]
Delete this file: `src/components/.vs/slnx.sqlite`

**Comment by divyaprakash-Rx** [comment]
@swapagarwal done.

**Comment by swapagarwal** [comment]
Thanks @divyaprakash-Rx! 👍

**Pull request merged**
