### PR TITLE
Added github anchor in svg form at the header to link to the repo

### LINKED ISSUE #10: Add the github icon in svg or png form in the Top right corner of header in jarvis web
When a user will click on this icon then it should show a pop-up type that will point the address of our GitHub Repo .

### PR DESCRIPTION
**Pull request by abhu-A-J**
fixes #10 

Added the link to GitHub repo on the header's navigation bar. Once clicked it will take you to the repository. A slight hover effect is added to make it look good esthetically.

**Edit**: Made the necessary changes as requested and now it looks like this.

Screenshot (36)

### CODE REVIEW

**Comment by tanisha03** [comment]
Screenshot from 2020-03-12 22-33-02
 you are expected to do something like this, in the top right corner

**Comment by abhu-A-J** [comment]
@tanisha03  sure, I'll make the changes.

**Comment by TeAmP0is0N** [comment]
@abhu-A-J Can you comment your SS?

**Comment by abhu-A-J** [comment]
@TeAmP0is0N Do these look okay now?? It's at the top right corner .

Screenshot (36)

**Comment by swapagarwal** [comment]
Needs rebase.

**Comment by tanisha03** [comment]
@abhu-A-J look into it

**Comment by abhu-A-J** [comment]
@tanisha03 does this looks fine now? He're's the screenshot on how it looks now

Screenshot (39)

**Comment by TeAmP0is0N** [comment]
@abhu-A-J Needs rebase. Solve it soon.

**Comment by swapagarwal** [comment]
Thanks @abhu-A-J! 👍

**Pull request merged**
