### PR TITLE
Added search and send icons

### LINKED ISSUE #28: Add Material Icons
Screenshot from 2020-04-06 15-00-09

Add appropriate material icon for Search bar and Send button.
Attach screenshots for reference.

### PR DESCRIPTION
**Pull request by abhu-A-J**
fixes #28 

@tanisha03  Ma'am are these okay??

**SCREENSHOTS**
Screenshot (98)

### CODE REVIEW

**Comment by tanisha03** [comment]
@abhu-A-J yes it's fine, just make the search icon a lil smaller is possible

**Comment by abhu-A-J** [comment]
> @abhu-A-J yes it's fine, just make the search icon a lil smaller is possible

Sure, I'll make the changes Ma'am!

**Comment by abhu-A-J** [comment]
@tanisha03  Ma'am I have made the changes. Now it looks like this:
Screenshot (99)

**Comment by swapagarwal** [comment]
Thanks @abhu-A-J! 👍

**Pull request merged**
